
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: learning_platform
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
